### ISSUE TITLE
I don't know what common good does

### ISSUE THREAD

**Issue by jedahan** [christianbundy/common-good#2]
Just reading the readme, I am not sure what common good does. Thankfully, I have encountered standard, so I am somewhat familiar. If I was new to the idea, it would be more confusing.

How about something like

> Common good checks javascript, typescript, css, and markdown files for common mistakes, and offers guidance on improving the state of your project. It uses popular tools for linting and formatting (such as eslint, stylelint, and prettier), and uses their default configurations to make it easier to bring on more contributors by having a consistent set of practices.

**Comment by christianbundy** [comment]
Thanks! That looks great to me, if you don't propose a PR I'll probably start a PR tomorrow with those words. That's a big improvement, thanks a bunch.

**Comment by christianbundy** [comment]
Just pushed an improvement, please let me know if there's anything unclear or if you'd prefer to see any changes!

**Comment by jedahan** [comment]
Sorry for unresponsiveness ive been one a vacation for a few days, this is great!
