### ISSUE TITLE
Should common-good ignore uncommitted files?

### ISSUE THREAD

**Issue by jedahan** [christianbundy/common-good#4]
I sometimes have scratch files that are not in gitignore, but are being checked with eslint and I don't really care if they are.

Should common good default to warn, but no exit code error if it finds stuff that isn't committed in git or other pms?

**Comment by christianbundy** [comment]
Yeah, I think we want something like [lint-staged](https://github.com/okonet/lint-staged) for this. My original CG was built on lint-staged, and it was great (and super fast!), but I reformatted my hard drive and have been too lazy to copy it from one of my backups. :sweat_smile:  This would make CG much faster for most people, so you only lint the files you changed, but our CI service can still run the tests on everything to make sure nothing slipped through.

**Comment by christianbundy** [comment]
resolved in 4.0.0! use `common-good test-staged` or `common-good fix-staged` for this :tada:
